# Generated by Django 4.2.20 on 2025-04-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blogpost'),
        ),
    ]
