# Generated by Django 4.2.20 on 2025-04-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_comment_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
