# Generated by Django 4.2.20 on 2025-05-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_course_alter_blogpost_image_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
