# Generated by Django 5.1.7 on 2025-05-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Sport', max_length=100),
            preserve_default=False,
        ),
    ]
