# Generated by Django 5.1.7 on 2025-05-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_course_created_at_video_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
    ]
