# Generated by Django 5.1.7 on 2025-05-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_video_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
    ]
